/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme="light"]'],
  theme: {
    extend: {
      colors: {
        // Anna Jóna color palette
        'primary': '#b64646',
        'secondary': '#DFA0A2',
        'background': '#f7e6e6',
        // Legacy colors (keeping for compatibility)
        navy: '#1e293b',
        charcoal: '#374151',
        peach: '#fb7185',
        'peach-light': '#fda4af',
        'peach-dark': '#e11d48',
        'warm-gray': '#f8f9fa',
        'soft-gray': '#e9ecef',
        'medium-gray': '#6c757d',
        'dark-gray': '#343a40',
        'accent': '#8b5a3c',
        'accent-light': '#a67c52',
        'accent-dark': '#6d4429',
      },
      fontFamily: {
        sans: ['Helvetica-Neue', 'system-ui', 'sans-serif'],
        display: ['Helvetica-Neue', 'system-ui', 'sans-serif'],
        body: ['EB Garamond', 'serif'],
        nav: ['Helvetica-Neue', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1.5' }],
        'sm': ['0.875rem', { lineHeight: '1.6' }],
        'base': ['1rem', { lineHeight: '1.7' }],
        'lg': ['1.125rem', { lineHeight: '1.7' }],
        'xl': ['1.25rem', { lineHeight: '1.6' }],
        '2xl': ['1.5rem', { lineHeight: '1.5' }],
        '3xl': ['1.875rem', { lineHeight: '1.4' }],
        '4xl': ['2.25rem', { lineHeight: '1.3' }],
        '5xl': ['3rem', { lineHeight: '1.2' }],
        '6xl': ['3.75rem', { lineHeight: '1.1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
        '34': '8.5rem',
        '38': '9.5rem',
        '42': '10.5rem',
        '46': '11.5rem',
        '50': '12.5rem',
      },
    },
  },
  plugins: [],
};
